name: Unit Tests

on:
  push:
    branches: 
        - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies from requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check for test files
        run: |
          if [ ! -d "tests" ] || [ -z "$(ls -A tests)" ]; then
            echo "No test files found. Skipping tests."
            exit 0
          fi

      - name: Test with unittest
        working-directory: tests
        run: python -m unittest discover -v
